apiVersion: v1
kind: Service
metadata:
  name: netflix-clone-service
spec:
  selector:
    app: netflix-clone
  ports:
  - protocol: TCP
    port: 80          # External port to expose the service
    targetPort: 80     # Port where the app listens
  type: LoadBalancer
