name: DevSecOps Netflix Clone

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Docker
        run: docker --version

      - name: Start Docker Service
        run: sudo service docker start

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag netflix-clone:latest

      - name: List Docker Images
        run: docker images

      - name: Save Docker Image as Artifact
        run: docker save netflix-clone:latest -o netflix-clone.tar
        
      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: netflix-clone.tar


  trivy_scan:
    runs-on: ubuntu-latest
    needs: build
    steps:


      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Load Docker Image
        run: docker load -i netflix-clone.tar
        
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Scan Docker Image
        run: trivy image netflix-clone:latest > trivy-report.txt

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.txt

  sonar_analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Load Docker Image
        run: docker load -i netflix-clone.tar

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=my-org
            -Dsonar.projectKey=netflix-clone 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  OWASP-Dependency-Check:
    needs: sonar_analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Install unzip (if not available)
      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      # Install OWASP Dependency-Check
      - name: Install OWASP Dependency-Check
        run: |
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v8.2.1/dependency-check-8.2.1-release.zip
          unzip dependency-check.zip -d $HOME/dependency-check
          chmod +x $HOME/dependency-check/dependency-check/bin/dependency-check.sh

      # Create output directory for reports
      - name: Create output directory
        run: mkdir -p dependency-check-report

     # Run OWASP Dependency-Check SCA
      - name: Run OWASP Dependency-Check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        continue-on-error: true
        run: |
          npm install
          $HOME/dependency-check/dependency-check/bin/dependency-check.sh \
            --project "My Project" \
            --scan $(pwd) \
            --format "ALL" \
            --out dependency-check-report \
            --failOnCVSS 9
