name: slack_github_action

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Slack notification
        uses: Ilshidur/action-slack@master
        env:
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
        with:
          args: "🚀 Code pushed to *${{ github.repository }}* on *${{ github.ref_name }}* by *${{ github.actor }}*. Commit message: _${{ github.event.head_commit.message }}_"
