name: slack_github_action

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification via curl
        run: |
          curl -X POST --data-urlencode \
          "payload={
            \"channel\": \"#igov-ci-notification\",
            \"username\": \"igov\",
            \"text\": \"🚀 Code pushed to *${{ github.repository }}* on branch *${{ github.ref_name }}* by *${{ github.actor }}*. Commit message: _${{ github.event.head_commit.message }}_\",
            \"icon_emoji\": \":robot_face:\"
          }" \
          $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
