name: slack_github_action

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        run: |
          curl -X POST --data-urlencode \
          "payload={
            \"channel\": \"#all-dextercyberlabs-testing-uat\",
            \"username\": \"GitHubBot\",
            \"text\": \"🚀 New push to *${{ github.repository }}* on branch *${{ github.ref_name }}* by *${{ github.actor }}*.\nMessage: _${{ github.event.head_commit.message }}_\",
            \"icon_emoji\": \":rocket:\"
          }" \
          $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
